use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'



target 'AHFMEpisodeListVCServices_Example' do
  pod 'AHFMEpisodeListVCServices', :path => '../'

  target 'AHFMEpisodeListVCServices_Tests' do
    inherit! :search_paths

    
  end
end
